// GENERATED — do not edit by hand. Regenerate with the backend's
// scripts/gen_kundali_hi.py after the engine's Hindi catalog changes.
// ignore_for_file: lines_longer_than_80_chars

/// Engine terms → Hindi (engine/locale/hi.py WORDS).
const kHiTerms = <String, String>{
  'Sun': 'सूर्य',
  'Moon': 'चंद्र',
  'Mars': 'मंगल',
  'Mercury': 'बुध',
  'Jupiter': 'गुरु',
  'Venus': 'शुक्र',
  'Saturn': 'शनि',
  'Rahu': 'राहु',
  'Ketu': 'केतु',
  'Aries': 'मेष',
  'Taurus': 'वृषभ',
  'Gemini': 'मिथुन',
  'Cancer': 'कर्क',
  'Leo': 'सिंह',
  'Virgo': 'कन्या',
  'Libra': 'तुला',
  'Scorpio': 'वृश्चिक',
  'Sagittarius': 'धनु',
  'Capricorn': 'मकर',
  'Aquarius': 'कुंभ',
  'Pisces': 'मीन',
  'Ashwini': 'अश्विनी',
  'Bharani': 'भरणी',
  'Krittika': 'कृत्तिका',
  'Rohini': 'रोहिणी',
  'Mrigashira': 'मृगशिरा',
  'Ardra': 'आर्द्रा',
  'Punarvasu': 'पुनर्वसु',
  'Pushya': 'पुष्य',
  'Ashlesha': 'आश्लेषा',
  'Magha': 'मघा',
  'Purva Phalguni': 'पूर्व फाल्गुनी',
  'Uttara Phalguni': 'उत्तर फाल्गुनी',
  'Hasta': 'हस्त',
  'Chitra': 'चित्रा',
  'Swati': 'स्वाति',
  'Vishakha': 'विशाखा',
  'Anuradha': 'अनुराधा',
  'Jyeshtha': 'ज्येष्ठा',
  'Mula': 'मूल',
  'Purva Ashadha': 'पूर्वाषाढ़ा',
  'Uttara Ashadha': 'उत्तराषाढ़ा',
  'Shravana': 'श्रवण',
  'Dhanishta': 'धनिष्ठा',
  'Shatabhisha': 'शतभिषा',
  'Purva Bhadrapada': 'पूर्व भाद्रपद',
  'Uttara Bhadrapada': 'उत्तर भाद्रपद',
  'Revati': 'रेवती',
  'Adhi Yoga': 'अधि योग',
  'Amala Yoga': 'अमला योग',
  'Anapha Yoga': 'अनफा योग',
  'Budhaditya Yoga': 'बुधादित्य योग',
  'Chamara Yoga': 'चामर योग',
  'Chandra-Mangala Yoga': 'चंद्र-मंगल योग',
  'Daridra Yoga': 'दरिद्र योग',
  'Dhana Yoga': 'धन योग',
  'Durudhara Yoga': 'दुरुधरा योग',
  'Gajakesari Yoga': 'गजकेसरी योग',
  'Kaal Sarpa Yoga': 'कालसर्प योग',
  'Kahala Yoga': 'काहल योग',
  'Kalanidhi Yoga': 'कलानिधि योग',
  'Kemadruma Yoga': 'केमद्रुम योग',
  'Lakshmi Yoga': 'लक्ष्मी योग',
  'Lakshmi-class Dhana Yoga': 'लक्ष्मी-श्रेणी धन योग',
  'Neechabhanga Raja Yoga': 'नीचभंग राज योग',
  'Papa Kartari Yoga': 'पाप कर्तरी योग',
  'Parvata Yoga': 'पर्वत योग',
  'Pushkala Yoga': 'पुष्कल योग',
  'Raja Yoga': 'राज योग',
  'Saraswati Yoga': 'सरस्वती योग',
  'Shakata Yoga': 'शकट योग',
  'Shankha Yoga': 'शंख योग',
  'Shubha Kartari Yoga': 'शुभ कर्तरी योग',
  'Sunapha Yoga': 'सुनफा योग',
  'Ubhayachari Yoga': 'उभयचरी योग',
  'Vasi Yoga': 'वासि योग',
  'Vasumati Yoga': 'वसुमति योग',
  'Vesi Yoga': 'वेशि योग',
  'Vish Yoga': 'विष योग',
  'Ruchaka Yoga': 'रुचक योग',
  'Bhadra Yoga': 'भद्र योग',
  'Hamsa Yoga': 'हंस योग',
  'Malavya Yoga': 'मालव्य योग',
  'Sasa Yoga': 'शश योग',
  'Harsha Vipreet Raja Yoga': 'हर्ष विपरीत राज योग',
  'Sarala Vipreet Raja Yoga': 'सरल विपरीत राज योग',
  'Vimala Vipreet Raja Yoga': 'विमल विपरीत राज योग',
  'Maha Parivartana Yoga': 'महा परिवर्तन योग',
  'Khala Parivartana Yoga': 'खल परिवर्तन योग',
  'Dainya Parivartana Yoga': 'दैन्य परिवर्तन योग',
  'Angarak Dosha': 'अंगारक दोष',
  'Daridra Dosha': 'दरिद्र दोष',
  'Gandmool Dosha': 'गंडमूल दोष',
  'Grahan Dosha': 'ग्रहण दोष',
  'Guru Chandal Dosha': 'गुरु चांडाल दोष',
  'Kaal Sarpa Dosha': 'कालसर्प दोष',
  'Kemadruma Dosha': 'केमद्रुम दोष',
  'Mangal Dosha': 'मंगल दोष',
  'Pitra Dosha': 'पितृ दोष',
  'Shrapit Dosha': 'श्रापित दोष',
  'identity, authority, recognition and the father': 'पहचान, अधिकार, मान-सम्मान और पिता',
  'the mind, moods, home, mother and public life': 'मन, मनोदशा, घर, माता और सार्वजनिक जीवन',
  'drive, courage, property, competition and a shorter temper': 'प्रेरणा, साहस, संपत्ति, प्रतिस्पर्धा और जल्दी आने वाला गुस्सा',
  'learning, communication, trade, contracts and skill': 'शिक्षा, संवाद, व्यापार, अनुबंध और कौशल',
  'growth, wisdom, teachers, children, faith and good counsel': 'विकास, ज्ञान, गुरु, संतान, आस्था और अच्छी सलाह',
  'relationships, comfort, art, vehicles, money and pleasure': 'रिश्ते, सुख-सुविधा, कला, वाहन, धन और आनंद',
  'hard work, discipline, delay, responsibility and slow, lasting results': 'कड़ी मेहनत, अनुशासन, देरी, ज़िम्मेदारी और धीमे पर स्थायी परिणाम',
  'ambition, the unconventional, foreign matters, technology and sudden turns': 'महत्वाकांक्षा, अपरंपरागत बातें, विदेश से जुड़े विषय, तकनीक और अचानक मोड़',
  'detachment, endings, research, spirituality and a turning inward': 'वैराग्य, समापन, शोध, आध्यात्मिकता और भीतर की ओर मुड़ना',
  'the self, health and how you show up': 'स्वयं, स्वास्थ्य और आप कैसे प्रस्तुत होते हैं',
  'money, savings, family and speech': 'धन, बचत, परिवार और वाणी',
  'effort, courage, siblings and short travel': 'प्रयास, साहस, भाई-बहन और छोटी यात्राएँ',
  'home, mother, land, vehicles and inner peace': 'घर, माता, भूमि, वाहन और मन की शांति',
  'children, education, creativity and romance': 'संतान, शिक्षा, रचनात्मकता और प्रेम',
  'work, service, debt, health routines and rivals': 'काम, सेवा, ऋण, स्वास्थ्य की दिनचर्या और प्रतिद्वंद्वी',
  'marriage, partnership and business dealings': 'विवाह, साझेदारी और व्यावसायिक लेन-देन',
  'change, upheaval, shared resources and the hidden': 'परिवर्तन, उथल-पुथल, साझा संसाधन और गुप्त विषय',
  'fortune, higher learning, dharma, mentors and long travel': 'भाग्य, उच्च शिक्षा, धर्म, मार्गदर्शक और लंबी यात्राएँ',
  'career, status and public standing': 'करियर, प्रतिष्ठा और सार्वजनिक स्थान',
  'income, gains, networks and elder siblings': 'आय, लाभ, संपर्क और बड़े भाई-बहन',
  'expenses, foreign lands, retreat, rest and letting go': 'खर्च, विदेश, एकांत, विश्राम और त्याग',
  'the two work smoothly together': 'दोनों सहजता से साथ काम करते हैं',
  'the two support each other': 'दोनों एक-दूसरे का साथ देते हैं',
  'the maha lord\'s own themes come to the front': 'महादशा स्वामी के अपने विषय सामने आते हैं',
  'the two themes run side by side': 'दोनों विषय साथ-साथ चलते हैं',
  'expect some friction between the two agendas': 'दोनों के उद्देश्यों में कुछ टकराव की अपेक्षा करें',
  'the two pull in different directions — pick your battles': 'दोनों अलग-अलग दिशाओं में खींचते हैं — सोच-समझकर मोर्चे चुनें',
  'leadership, will and a wish to stand on your own feet': 'नेतृत्व, इच्छाशक्ति और अपने पैरों पर खड़े होने की चाह',
  'sensitivity, partnership and a diplomatic, feeling nature': 'संवेदनशीलता, साझेदारी और कूटनीतिक, भावुक स्वभाव',
  'expression, optimism, teaching and a love of learning': 'अभिव्यक्ति, आशावाद, अध्यापन और सीखने का प्रेम',
  'an unconventional, systems-minded streak that questions the given order': 'एक अपरंपरागत, व्यवस्थित सोच जो स्थापित ढर्रे पर प्रश्न उठाती है',
  'quickness, communication, trade and a restless need for variety': 'तेज़ी, संवाद, व्यापार और विविधता की बेचैन चाह',
  'warmth, responsibility for others, beauty and home': 'स्नेह, दूसरों के प्रति ज़िम्मेदारी, सौंदर्य और घर',
  'an inward, researching, spiritual turn of mind': 'भीतर झाँकने वाला, शोधपरक, आध्यात्मिक मन',
  'endurance, structure, delayed but lasting results and hard-won authority': 'सहनशक्ति, व्यवस्था, देर से पर स्थायी परिणाम और मेहनत से पाया अधिकार',
  'energy, courage, drive and a protective temper': 'ऊर्जा, साहस, प्रेरणा और रक्षक स्वभाव',
  'few numbers': 'कुछ ही अंकों',
  'Sunday': 'रविवार',
  'Monday': 'सोमवार',
  'Tuesday': 'मंगलवार',
  'Wednesday': 'बुधवार',
  'Thursday': 'गुरुवार',
  'Friday': 'शुक्रवार',
  'Saturday': 'शनिवार',
  'gold': 'सुनहरा',
  'orange': 'नारंगी',
  'yellow': 'पीला',
  'white': 'सफ़ेद',
  'cream': 'क्रीम',
  'silver': 'चाँदी-सा',
  'violet': 'बैंगनी',
  'grey': 'स्लेटी',
  'blue': 'नीला',
  'khaki': 'खाकी',
  'green': 'हरा',
  'light grey': 'हल्का स्लेटी',
  'pink': 'गुलाबी',
  'pale blue': 'हल्का नीला',
  'light green': 'हल्का हरा',
  'smoke': 'धुएँ-सा',
  'dark blue': 'गहरा नीला',
  'black': 'काला',
  'purple': 'जामुनी',
  'red': 'लाल',
  'coral': 'मूंगिया',
  'East': 'पूर्व',
  'West': 'पश्चिम',
  'North': 'उत्तर',
  'South': 'दक्षिण',
  'North-East': 'उत्तर-पूर्व',
  'North-West': 'उत्तर-पश्चिम',
  'South-East': 'दक्षिण-पूर्व',
  'South-West': 'दक्षिण-पश्चिम',
  'Surya': 'सूर्य देव',
  'Chandra / Parvati': 'चंद्र / पार्वती',
  'Brihaspati / Vishnu': 'बृहस्पति / विष्णु',
  'Durga': 'दुर्गा',
  'Vishnu / Ganesha': 'विष्णु / गणेश',
  'Lakshmi': 'लक्ष्मी',
  'Ganesha / Ketu': 'गणेश / केतु',
  'Shani / Hanuman': 'शनि / हनुमान',
  'Hanuman / Kartikeya': 'हनुमान / कार्तिकेय',
  'ruby': 'माणिक्य',
  'pearl': 'मोती',
  'yellow sapphire': 'पुखराज',
  'hessonite (gomed)': 'गोमेद',
  'emerald': 'पन्ना',
  'diamond / white sapphire': 'हीरा / सफ़ेद पुखराज',
  'cat\'s eye (lehsunia)': 'लहसुनिया',
  'blue sapphire': 'नीलम',
  'red coral': 'मूंगा',
  'mind': 'मन',
  'heart': 'हृदय',
  'action': 'कर्म',
  'thought': 'विचार',
  'will': 'इच्छाशक्ति',
  'activity': 'सक्रियता',
  'determination': 'दृढ़ता',
  'spirituality': 'आध्यात्मिकता',
  'the plane of the mind — thought, memory and imagination': 'मन का तल — विचार, स्मृति और कल्पना',
  'the plane of feeling — love, freedom and creativity': 'भावना का तल — प्रेम, स्वतंत्रता और रचनात्मकता',
  'the plane of action — the practical, physical, doing side': 'कर्म का तल — व्यावहारिक, शारीरिक, करने वाला पक्ष',
  'the plane of the planner — analysis and order': 'योजनाकार का तल — विश्लेषण और व्यवस्था',
  'the plane of will — determination and self-belief': 'इच्छा का तल — दृढ़ता और आत्मविश्वास',
  'the plane of activity — energy put into the world': 'सक्रियता का तल — दुनिया में लगाई ऊर्जा',
  'the golden line of willpower and drive': 'इच्छाशक्ति और प्रेरणा की स्वर्ण रेखा',
  'the silver line of compassion and the inner search': 'करुणा और आंतरिक खोज की रजत रेखा',
  'rising': 'आरंभ',
  'peak': 'चरम',
  'setting': 'उतार',
  'kantaka': 'कंटक',
  'ashtama': 'अष्टम',
  'the first phase — endings, expenses and a slow inward turn as the load builds': 'पहला चरण — भार बढ़ने के साथ समापन, खर्च और धीरे-धीरे भीतर की ओर मुड़ना',
  'the middle and heaviest phase — Saturn on the Moon tests health, mood and self': 'बीच का और सबसे भारी चरण — चंद्रमा पर शनि स्वास्थ्य, मनोदशा और स्वयं की परीक्षा लेता है',
  'the closing phase — money and family matters settle as the load eases': 'अंतिम चरण — भार घटने के साथ धन और परिवार के विषय स्थिर होते हैं',
  'Kantaka Shani (4th) — home, peace of mind and property feel the friction': 'कंटक शनि (चौथा) — घर, मन की शांति और संपत्ति में घर्षण',
  'Ashtama Shani (8th) — a demanding transit for health, obstacles and change': 'अष्टम शनि (आठवाँ) — स्वास्थ्य, बाधाओं और परिवर्तन के लिए कठिन गोचर',
  'authority, recognition and vitality': 'अधिकार, मान-सम्मान और जीवनशक्ति',
  'mood, comfort and public dealings': 'मनोदशा, सुख और सार्वजनिक व्यवहार',
  'energy, initiative and disputes': 'ऊर्जा, पहल और विवाद',
  'communication, trade and paperwork': 'संवाद, व्यापार और काग़ज़ी काम',
  'growth, opportunity, learning and money': 'विकास, अवसर, शिक्षा और धन',
  'relationships, comfort and money': 'रिश्ते, सुख और धन',
  'responsibility, effort, delay and discipline': 'ज़िम्मेदारी, प्रयास, देरी और अनुशासन',
  'udveg': 'उद्वेग',
  'char': 'चर',
  'labh': 'लाभ',
  'amrit': 'अमृत',
  'kaal': 'काल',
  'shubh': 'शुभ',
  'rog': 'रोग',
  'abhijit': 'अभिजित',
  'good': 'शुभ',
  'neutral': 'सामान्य',
  'bad': 'अशुभ',
  'favourable': 'अनुकूल',
  'caution': 'सावधानी वाला',
  'authority, government and health matters': 'अधिकार, सरकारी और स्वास्थ्य संबंधी काम',
  'travel, home, water and public dealings': 'यात्रा, घर, जल और सार्वजनिक व्यवहार',
  'energy, disputes, property and machinery': 'ऊर्जा, विवाद, संपत्ति और मशीनरी',
  'study, trade, writing and negotiation': 'पढ़ाई, व्यापार, लेखन और बातचीत',
  'learning, money, ceremonies and advice': 'शिक्षा, धन, संस्कार और सलाह',
  'relationships, art, purchases and comfort': 'रिश्ते, कला, ख़रीदारी और सुख',
  'labour, repairs, iron and long-term work': 'श्रम, मरम्मत, लोहा और लंबे समय का काम',
  'moolatrikona': 'मूलत्रिकोण',
  'own': 'स्वराशि',
  'great friend sign': 'अतिमित्र राशि',
  'friend sign': 'मित्र राशि',
  'enemy sign': 'शत्रु राशि',
  'great enemy sign': 'अतिशत्रु राशि',
  'Ruby': 'माणिक्य',
  'Pearl': 'मोती',
  'Red Coral': 'मूंगा',
  'Emerald': 'पन्ना',
  'Yellow Sapphire': 'पुखराज',
  'Diamond': 'हीरा',
  'Blue Sapphire': 'नीलम',
  'Hessonite (Gomed)': 'गोमेद',
  'Cat\'s Eye (Lehsunia)': 'लहसुनिया',
  'Surya / Lord Rama': 'सूर्य / भगवान राम',
  'Mangal / Hanuman / Kartikeya': 'मंगल / हनुमान / कार्तिकेय',
  'Budha / Vishnu / Ganesha': 'बुध / विष्णु / गणेश',
  'Brihaspati / Vishnu / Dakshinamurthy': 'बृहस्पति / विष्णु / दक्षिणामूर्ति',
  'Shukra / Lakshmi': 'शुक्र / लक्ष्मी',
  'Shani / Hanuman / Bhairava': 'शनि / हनुमान / भैरव',
  'Rahu / Durga': 'राहु / दुर्गा',
  'Ketu / Ganesha': 'केतु / गणेश',
  'Om Suryaya Namah': 'ॐ सूर्याय नमः',
  'Om Chandraya Namah': 'ॐ चन्द्राय नमः',
  'Om Angarakaya Namah': 'ॐ अङ्गारकाय नमः',
  'Om Budhaya Namah': 'ॐ बुधाय नमः',
  'Om Gurave Namah': 'ॐ गुरवे नमः',
  'Om Shukraya Namah': 'ॐ शुक्राय नमः',
  'Om Shanaishcharaya Namah': 'ॐ शनैश्चराय नमः',
  'Om Rahave Namah': 'ॐ राहवे नमः',
  'Om Ketave Namah': 'ॐ केतवे नमः',
  'smoky grey': 'धुएँ-सा स्लेटी',
  'brown': 'भूरा',
  'multi-colour': 'बहुरंगी',
  '1 or 12 mukhi': '1 या 12 मुखी',
  '2 mukhi': '2 मुखी',
  '3 mukhi': '3 मुखी',
  '4 mukhi': '4 मुखी',
  '5 mukhi': '5 मुखी',
  '6 or 13 mukhi': '6 या 13 मुखी',
  '7 or 14 mukhi': '7 या 14 मुखी',
  '8 mukhi': '8 मुखी',
  '9 mukhi': '9 मुखी',
  'wheat, jaggery or copper on a Sunday': 'रविवार को गेहूँ, गुड़ या तांबा',
  'rice, milk or silver on a Monday': 'सोमवार को चावल, दूध या चाँदी',
  'red lentils (masoor) or a red cloth on a Tuesday': 'मंगलवार को मसूर दाल या लाल कपड़ा',
  'green gram (moong) or a green cloth on a Wednesday': 'बुधवार को मूंग या हरा कपड़ा',
  'turmeric, chana dal or a yellow cloth on a Thursday': 'गुरुवार को हल्दी, चना दाल या पीला कपड़ा',
  'white sweets, curd or a white cloth on a Friday': 'शुक्रवार को सफ़ेद मिठाई, दही या सफ़ेद कपड़ा',
  'black sesame, mustard oil or iron on a Saturday': 'शनिवार को काले तिल, सरसों का तेल या लोहा',
  'coconut, blanket or mustard oil on a Saturday': 'शनिवार को नारियल, कंबल या सरसों का तेल',
  'a multicoloured blanket or sesame on a Wednesday': 'बुधवार को बहुरंगी कंबल या तिल',
  'Pitri Rin — debt of the ancestors / father\'s line': 'पितृ ऋण — पूर्वजों / पिता के वंश का ऋण',
  'Pitri Rin': 'पितृ ऋण',
  'Matri Rin — debt of the mother': 'मातृ ऋण — माता का ऋण',
  'Matri Rin': 'मातृ ऋण',
  'Stri Rin — debt owed to a wife / woman of the house': 'स्त्री ऋण — पत्नी / घर की स्त्री का ऋण',
  'Stri Rin': 'स्त्री ऋण',
  'Kanya / Santan Rin — debt of a daughter or child': 'कन्या / संतान ऋण — बेटी या संतान का ऋण',
  'Kanya / Santan Rin': 'कन्या / संतान ऋण',
  'Bandhu Rin — debt of brothers / kin': 'बंधु ऋण — भाइयों / संबंधियों का ऋण',
  'Bandhu Rin': 'बंधु ऋण',
  'Atma / Karz Rin — debt of one\'s own past actions': 'आत्म / कर्ज़ ऋण — अपने पिछले कर्मों का ऋण',
  'Atma / Karz Rin': 'आत्म / कर्ज़ ऋण',
  'the self, health, initiative and how the year starts': 'स्वयं, स्वास्थ्य, पहल और वर्ष की शुरुआत',
  'money, savings, family and food': 'धन, बचत, परिवार और भोजन',
  'effort, courage, siblings, short trips and communication': 'प्रयास, साहस, भाई-बहन, छोटी यात्राएँ और संवाद',
  'home, property, vehicles, mother and peace of mind': 'घर, संपत्ति, वाहन, माता और मन की शांति',
  'children, learning, romance, speculation and creativity': 'संतान, शिक्षा, प्रेम, सट्टा-निवेश और रचनात्मकता',
  'work, service, competition, debt and health routines': 'काम, सेवा, प्रतिस्पर्धा, ऋण और स्वास्थ्य की दिनचर्या',
  'marriage, partnership, travel and public dealings': 'विवाह, साझेदारी, यात्रा और सार्वजनिक व्यवहार',
  'change, obstacles, shared money, and things hidden — a year to be careful': 'परिवर्तन, बाधाएँ, साझा धन और छिपी बातें — सावधान रहने का वर्ष',
  'fortune, dharma, mentors, long journeys and higher study': 'भाग्य, धर्म, मार्गदर्शक, लंबी यात्राएँ और उच्च शिक्षा',
  'career, status, authority and public work': 'करियर, प्रतिष्ठा, अधिकार और सार्वजनिक काम',
  'gains, income, friends and fulfilled wishes': 'लाभ, आय, मित्र और पूरी होती इच्छाएँ',
  'expense, rest, foreign lands, letting go and spiritual practice': 'खर्च, विश्राम, विदेश, त्याग और आध्यात्मिक साधना',
  'Lagna': 'लग्न',
  'Anant': 'अनंत',
  'Kulik': 'कुलिक',
  'Vasuki': 'वासुकि',
  'Shankhpal': 'शंखपाल',
  'Padma': 'पद्म',
  'Mahapadma': 'महापद्म',
  'Takshak': 'तक्षक',
  'Karkotak': 'कर्कोटक',
  'Shankhachur': 'शंखचूड़',
  'Ghatak': 'घातक',
  'Vishdhar': 'विषधर',
  'Sheshnag': 'शेषनाग',
  'challenging': 'चुनौतीपूर्ण',
  'balanced': 'संतुलित',
  'supportive': 'सहायक',
  'exalted': 'उच्च',
  'in moolatrikona': 'मूलत्रिकोण में',
  'in its own sign': 'स्वराशि में',
  'in a great friend\'s sign': 'अतिमित्र की राशि में',
  'in a friendly sign': 'मित्र राशि में',
  'in a neutral sign': 'सम राशि में',
  'in an enemy\'s sign': 'शत्रु राशि में',
  'in a great enemy\'s sign': 'अतिशत्रु की राशि में',
  'debilitated': 'नीच',
  'a character of its own': 'एक अपना ही स्वभाव',
  'bold, direct, quick to act and quick to move on': 'साहसी, स्पष्टवादी, जल्दी काम करने और जल्दी आगे बढ़ने वाला',
  'steady, patient, fond of comfort and the tangible': 'स्थिर, धैर्यवान, सुख-सुविधा और ठोस चीज़ों का प्रेमी',
  'curious, talkative, mentally restless and adaptable': 'जिज्ञासु, बातूनी, मानसिक रूप से चंचल और ढल जाने वाला',
  'sensitive, protective, guided by mood and memory': 'संवेदनशील, रक्षा करने वाला, मनोदशा और स्मृतियों से प्रेरित',
  'warm, proud, wants to lead and to be recognised': 'स्नेही, स्वाभिमानी, नेतृत्व और पहचान चाहने वाला',
  'analytical, careful, improvement-minded and modest': 'विश्लेषणात्मक, सावधान, सुधार की सोच वाला और विनम्र',
  'fair, sociable, seeks balance and good company': 'न्यायप्रिय, मिलनसार, संतुलन और अच्छी संगत चाहने वाला',
  'intense, private, all-or-nothing, hard to read': 'तीव्र, निजी, सब-कुछ-या-कुछ-नहीं, जिसे समझना कठिन हो',
  'candid, optimistic, freedom-loving, believes in a bigger picture': 'स्पष्टवादी, आशावादी, स्वतंत्रता-प्रेमी, बड़े उद्देश्य में विश्वास रखने वाला',
  'disciplined, ambitious, patient with the long climb': 'अनुशासित, महत्वाकांक्षी, लंबी चढ़ाई में धैर्य रखने वाला',
  'independent, unconventional, thinks in systems': 'स्वतंत्र, अपरंपरागत, व्यवस्थाओं में सोचने वाला',
  'imaginative, compassionate, easily moved, dislikes hard edges': 'कल्पनाशील, करुणामय, जल्दी भावुक होने वाला, कठोरता से दूर रहने वाला',
  'usually a lean, active build and a direct expression': 'आमतौर पर दुबली, सक्रिय काया और सीधा भाव',
  'often a solid, well-set frame and pleasant features': 'अक्सर मज़बूत, सुगठित शरीर और सुखद नैन-नक्श',
  'typically tall or wiry, expressive hands and face': 'आमतौर पर लंबा या छरहरा, भावपूर्ण हाथ और चेहरा',
  'a rounder face, softer build, changeable complexion': 'गोल चेहरा, कोमल काया, बदलता रंग-रूप',
  'an upright carriage, broad forehead, commanding look': 'सीधी चाल, चौड़ा माथा, प्रभावशाली रूप',
  'a neat, medium build and a youthful appearance': 'सुघड़, मध्यम काया और युवा रूप',
  'even, well-proportioned features and an easy smile': 'संतुलित, सुडौल नैन-नक्श और सहज मुस्कान',
  'a strong, compact build and a penetrating gaze': 'मज़बूत, गठीली काया और भेदती दृष्टि',
  'a tall or large frame, open face, athletic in youth': 'लंबा या बड़ा शरीर, खुला चेहरा, युवावस्था में खिलाड़ी जैसा',
  'a lean, bony frame, serious cast to the features': 'दुबला, हड्डीदार शरीर, गंभीर नैन-नक्श',
  'a tall or long-limbed build and an unhurried manner': 'लंबी या लंबे अंगों वाली काया और इत्मीनान भरा ढंग',
  'soft features, expressive eyes, a fuller build later': 'कोमल नैन-नक्श, भावपूर्ण आँखें, बाद में भरा हुआ शरीर',
  'a spirited, independent partner who takes the initiative': 'जोशीला, स्वतंत्र जीवनसाथी जो पहल करता हो',
  'a steady, home-loving partner who values security': 'स्थिर, घर-प्रेमी जीवनसाथी जो सुरक्षा को महत्व देता हो',
  'a clever, communicative partner, often younger in spirit': 'चतुर, संवादप्रिय जीवनसाथी, अक्सर मन से युवा',
  'a caring, family-centred, emotionally attuned partner': 'देखभाल करने वाला, परिवार-केंद्रित, भावनात्मक रूप से जुड़ा जीवनसाथी',
  'a confident, generous partner who likes to be admired': 'आत्मविश्वासी, उदार जीवनसाथी जिसे प्रशंसा पसंद हो',
  'a practical, discerning partner attentive to detail': 'व्यावहारिक, विवेकी जीवनसाथी जो बारीकियों पर ध्यान दे',
  'a charming, relationship-minded, socially graceful partner': 'आकर्षक, रिश्तों को महत्व देने वाला, सामाजिक रूप से शालीन जीवनसाथी',
  'an intense, loyal, deeply private partner': 'तीव्र, वफ़ादार, बहुत निजी स्वभाव का जीवनसाथी',
  'an honest, freedom-loving, well-travelled or learned partner': 'ईमानदार, स्वतंत्रता-प्रेमी, यात्रा-अनुभवी या विद्वान जीवनसाथी',
  'a mature, responsible partner, sometimes older or established': 'परिपक्व, ज़िम्मेदार जीवनसाथी, कभी-कभी उम्र में बड़ा या स्थापित',
  'an unconventional, independent-minded partner and friend first': 'अपरंपरागत, स्वतंत्र सोच वाला जीवनसाथी जो पहले मित्र हो',
  'a gentle, imaginative, self-sacrificing partner': 'सौम्य, कल्पनाशील, त्यागी जीवनसाथी',
  'Marriage': 'विवाह',
  'Job': 'नौकरी',
  'Promotion': 'पदोन्नति',
  'Business': 'व्यापार',
  'Property': 'संपत्ति',
  'Loan Money': 'ऋण और धन',
  'Childbirth': 'संतान प्राप्ति',
  'Foreign Travel': 'विदेश यात्रा',
  'Litigation': 'मुकदमा',
  'Health': 'स्वास्थ्य',
  'Lost Item': 'खोई वस्तु',
  'Reunion': 'पुनर्मिलन',
  'General': 'सामान्य',
  'your health, drive and how you present yourself': 'आपका स्वास्थ्य, ऊर्जा और आप स्वयं को कैसे प्रस्तुत करते हैं',
  'effort, courage, communication and short travel': 'प्रयास, साहस, संवाद और छोटी यात्राएं',
  'home, property, vehicles and peace of mind': 'घर, संपत्ति, वाहन और मन की शांति',
  'children, learning, romance and creativity': 'संतान, शिक्षा, प्रेम और रचनात्मकता',
  'work, service, health routines, debt and rivals': 'काम, सेवा, स्वास्थ्य की दिनचर्या, कर्ज़ और प्रतिद्वंद्वी',
  'marriage, partnership and one-to-one dealings': 'विवाह, साझेदारी और आमने-सामने के व्यवहार',
  'shared money, change and matters below the surface — go carefully': 'साझा धन, परिवर्तन और छिपे हुए विषय — सावधानी से चलें',
  'fortune, higher study, mentors and long journeys': 'भाग्य, उच्च शिक्षा, मार्गदर्शक और लंबी यात्राएं',
  'income, gains, friends and networks': 'आय, लाभ, मित्र और संपर्क',
  'expenses, rest, foreign matters and letting go': 'खर्च, विश्राम, विदेश से जुड़े विषय और छोड़ना सीखना',
};

/// Chart type (d9, moon, chalit, transit) → its name.
const kHiChartNames = <String, String>{
  'd1': 'राशि',
  'd2': 'होरा',
  'd3': 'द्रेष्काण',
  'd4': 'चतुर्थांश',
  'd5': 'पंचमांश',
  'd6': 'षष्ठांश',
  'd7': 'सप्तमांश',
  'd8': 'अष्टमांश',
  'd9': 'नवमांश',
  'd10': 'दशमांश',
  'd11': 'रुद्रांश',
  'd12': 'द्वादशांश',
  'd16': 'षोडशांश',
  'd20': 'विंशांश',
  'd24': 'चतुर्विंशांश',
  'd27': 'सप्तविंशांश',
  'd30': 'त्रिंशांश',
  'd40': 'चत्वारिंशांश',
  'd45': 'अक्षवेदांश',
  'd60': 'षष्ट्यंश',
  'moon': 'चंद्र कुंडली',
  'chalit': 'भाव चलित',
  'transit': 'गोचर',
};

/// Chart type → what it is read for.
const kHiChartSignifies = <String, String>{
  'd1': 'शरीर, संपूर्ण जीवन, सब कुछ',
  'd2': 'धन, आर्थिक समृद्धि',
  'd3': 'भाई-बहन, साहस, पहल',
  'd4': 'भाग्य, संपत्ति, अचल संपत्ति, घर',
  'd5': 'यश, अधिकार, आध्यात्मिक पुण्य',
  'd6': 'स्वास्थ्य, रोग, ऋण, शत्रु',
  'd7': 'संतान, वंश, रचनात्मकता',
  'd8': 'आकस्मिक घटनाएँ, आयु संबंधी कष्ट, बाधाएँ',
  'd9': 'जीवनसाथी, धर्म, अंतर्मन — मुख्य सहायक कुंडली',
  'd10': 'करियर, व्यवसाय, प्रतिष्ठा, उपलब्धि',
  'd11': 'मृत्यु, विनाश, विपत्ति से लाभ',
  'd12': 'माता-पिता, पूर्वज, विरासत में मिला कर्म',
  'd16': 'वाहन, सुख-सुविधाएँ, विलासिता, प्रसन्नता',
  'd20': 'आध्यात्मिक साधना, पूजा, भक्ति',
  'd24': 'शिक्षा, विद्या, ज्ञान',
  'd27': 'शक्ति और दुर्बलता, सहनशक्ति',
  'd30': 'दुर्भाग्य, अनिष्ट, नैतिक चरित्र',
  'd40': 'मातृ विरासत, शुभ/अशुभ प्रभाव',
  'd45': 'पितृ विरासत, समग्र चरित्र और आचरण',
  'd60': 'पूर्व जन्म के कर्म, सबसे सूक्ष्म स्तर — समग्र',
  'moon': 'मन और भावनाएँ — चंद्रमा से पढ़ी गई राशि कुंडली',
  'chalit': 'वास्तविक भाव संधियों (श्रीपति) के अनुसार भाव फल, पूर्ण राशि नहीं',
  'transit': 'जन्म कुंडली के भावों पर वर्तमान ग्रह',
};

/// The chart widgets' copy, by customer ARB key.
const kHiChartStrings = <String, String>{
  'kChartShortMoon': 'चंद्र',
  'kChartShortChalit': 'चलित',
  'kChartShortTransit': 'गोचर',
  'kChAscendant': 'लग्न',
  'kChLagnaVargottama': 'लग्न वर्गोत्तम',
  'kChAsOf': '{when} तक',
  'kChUnverified': 'यह वर्ग अभी DrikPanchang से सत्यापित नहीं है — ग्रह स्थितियों को प्रायोगिक मानें।',
  'kChChalitShiftedOne': '{planets} पूर्ण-राशि भाव से अलग भाव में है।',
  'kChChalitShiftedMany': '{planets} पूर्ण-राशि भाव से अलग भाव में हैं।',
  'kChColPlanet': 'ग्रह',
  'kChColSign': 'राशि',
  'kChColDegree': 'अंश',
  'kChColHouse': 'भाव',
  'kChColBhava': 'चलित भाव',
  'kChColFromMoon': 'चंद्र से',
  'kChLegend': 'संकेत',
  'kChLegendNote': '℞ वक्री   ⬦ वर्गोत्तम   ← बदला हुआ भाव (चलित)\nउत्तर भारतीय: खाने की संख्या = राशि (1 मेष … 12 मीन), पहला भाव ऊपर बीच में।',
  'kChNorthIndian': 'उत्तर भारतीय',
  'kChSouthIndian': 'दक्षिण भारतीय',
  'kChRasiNumbers': 'राशि संख्या',
  'kChHouseNumbers': 'भाव संख्या',
  'kChPickerCharts': 'कुंडलियाँ',
  'kChPickerDivisional': 'वर्ग कुंडलियाँ',
};
