// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKabXaG_z54cNiI7DHDyezFRkJ-X_kVKM',
    appId: '1:51248771144:web:6b4ed31ea4e7aa5575687d',
    messagingSenderId: '51248771144',
    projectId: 'talk-acharya-ji',
    authDomain: 'talk-acharya-ji.firebaseapp.com',
    storageBucket: 'talk-acharya-ji.firebasestorage.app',
    measurementId: 'G-P67WD1B0PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOSTYxca7XVNlF-_uXz3kYebpI5NYR4s',
    appId: '1:51248771144:android:21af65a6a6c44aa975687d',
    messagingSenderId: '51248771144',
    projectId: 'talk-acharya-ji',
    storageBucket: 'talk-acharya-ji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUi59pTD72bADexr82Np1rwa58nc6aMB4',
    appId: '1:51248771144:ios:0de83d7a31925f2275687d',
    messagingSenderId: '51248771144',
    projectId: 'talk-acharya-ji',
    storageBucket: 'talk-acharya-ji.firebasestorage.app',
    iosBundleId: 'com.talkacharya.astrologer',
  );
}
